logdna/logdna-agent-v2

Makefile, k8s/agent-namespace.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml, k8s/logdna-agent-st.yaml, k8s/logdna-agent.yaml, k8s/mock-ingester.yaml
This adds the app.kubernetes.io/{name,version,instance} labels to the kubernetes yaml and extends the existing version bump functionality in the makefile to update the version when a release is made.
=> Add k8s labels

k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml, k8s/logdna-agent-st.yaml, k8s/logdna-agent.yaml, k8s/mock-ingester.yaml
Reorders the k8s yamls so that items depended on by other items are created before their dependants.
=> Reorder kubernetes yamls with dependencies first

bin/src/main.rs, common/config/src/lib.rs
Previously the user agent was built using the CARGO_PKG and CARGO_PKG_VERSION for the common/config module which was statically included during compilation.
This PR changes the behaviour so that the main.rs statically includes it's CARGO_PKG and CARGO_PKG_VERSION which the config module references as an extern &'static str.
Before this change the user-agent string showed as:
`config/0.1.0 (Red Hat Enterprise Linux/8.2 (Ootpa))`
it now appears as:
`logdna-agent/2.1.9-beta.2 (Red Hat Enterprise Linux/8.2 (Ootpa))`
Internal Ref: LOG-7367
=> Use agent binary's CARGO_PKG/VERSION in useragent

Jenkinsfile, Makefile
Use a publicly available docker image as the default in the Makefile to ensure it's easy for the public to build the agent.
=> Point Makefile at public build image by default

Dockerfile, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml
This change gives the logdna-agent special read capabilities over the filesystem so we don't need to run as the root user. This alleviates a common security issue with the agent
=> Run logdna-agent as non-root user

Makefile
Example:
```
REPOSITORY                             TAG                  IMAGE ID            CREATED             SIZE
REPOSITORY                                    TAG                        IMAGE ID            CREATED             SIZE
us.gcr.io/logdna-k8s/logdna-agent-v2          2                          fec63c895146        43 minutes ago      185MB
us.gcr.io/logdna-k8s/logdna-agent-v2          2.2                        fec63c895146        43 minutes ago      185MB
us.gcr.io/logdna-k8s/logdna-agent-v2          2.2.0                      fec63c895146        43 minutes ago      185MB
us.gcr.io/logdna-k8s/logdna-agent-v2          2.2.0-build.fec63c895146   fec63c895146        43 minutes ago      185MB
logdna/logdna-agent                           2                          fec63c895146 …
```
=> Add unique tag that marks the hash of the build for each MAJOR.MINOR.PATCH version

Cargo.lock, common/fs/Cargo.toml, common/fs/src/error.rs, common/fs/src/lib.rs, common/http/Cargo.toml, common/http/src/lib.rs, common/http/src/retry.rs, common/k8s/Cargo.toml, common/k8s/src/errors.rs, common/k8s/src/lib.rs, common/k8s/src/middleware/metadata.rs
Thiserror (and it's partner crate Anyhow) are more or less the de-facto standard for managing custom error types in rust. thiserror operates as a proc macro so the compiler has an easier time looking inside it than with quick-error.
For example while porting over to it the compiler detected that the k8s::middleware::metadata::Error::Regex variant is actually dead code and never constructed.
=> Port from quickerror to thiserror

bin/src/main.rs, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml
Previously this would default to `error` or `warn` which confused some users with older yamls that did not specify a default in the environment variable.
=> Default the `RUST_LOG` env var to `info`

Dockerfile
Before this change a comment in the Dockerfile incorrectly mentions Ubuntu
After this change a comment correctly names the base image: https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=8.2&push_date=1599576716000
=> Refer to UBI not Ubuntu in Dockerfile comment

Jenkinsfile
The Jenkinsfile was incorrectly referencing `TRIGGER_STRING` which caused a Jenkins build error when going into the `Validate PR Source` stage.
This change fixes that and also makes the Jenkinsfile trigger command and error congruent with LogDNA's other public repos.
=> Fix invalid reference in Jenkinsfiles

Cargo.lock, Dockerfile, docs/README.md, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml
1. Make sure the group created in the Dockerfile is 5000 as intended
2. Give the `logdna` binary with the effective bit since it's not capability aware
3. Remove `securityContext` since we don't want to run as non-root in the default behavior
4. Add documentation about running as non-root
=> Fix some issues found with hardening the agent:

docs/README.md, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml
The linux cap `CAP_DAC_READ_SEARCH` needs to be enabled in the k8s yaml since the binary has the effective bit set. This is required regardless of running as root or non-root.
=> Add Kubernetes capabilities to the default yamls

common/fs/src/tail.rs, common/journald/src/stream.rs
Found an issue with Journald that occurs in the following scenario
1. The agent is already started and monitoring a journal such as `/var/log/journal`
2. The node does not currently have Journald logging enabled
3. Modifying the node to enable journald which results in the creation of a new subdirectory `/var/log/journal/<GUID>`
4. The agent will start going through all the stale journald records from the beginning and giving them the false timestamp of `now`
This issue occurs because we only seek the tail of the Journal stream on startup. This fix checks to make sure all records have a timestamp of within 30 seconds. If a timestamp is older than that, then the journal is reseeked to the end.
```
[2020-11-10T10:10:52Z WARN  journald::stream] Received a stale journald record, reseeking …
```
=> Fix bug where Journald ingests stale records

Jenkinsfile, Makefile
This fixes up the makefiles targets so that make release-minor will correctly create a minor beta version and make release will correctly strip the beta off the current  version in order to make it a full release
=> Fixup release-minor and release targets

bin/tests/cli.rs, bin/tests/common.rs
Generate a file that gets appended in the background and create an integration test that validates that the data is read by the agent.
For `start_append_to_file` fn in the tests, I've ended up using a separate thread for the file appends and use sync IO because I find it easier than doing it w/ tokio, given that is a test setup I hope its ok.
=> Test file appended in the background

Jenkinsfile
With this change, the Jenkins step waits for a few minutes for user input and in case
publishing canceled or timed out, the build is still marked as successful.
=> Make publishing image Jenkins step optional

bin/tests/cli.rs, bin/tests/common.rs, common/fs/src/cache/mod.rs
Add an integration test that uses nested directories w/ a symlink to the log directory that is removed.
Based on #63. 
This currently fails on master awaiting for the LOG-7968 fix.
=> Test removing linked nested directories

Cargo.lock, common/http/Cargo.toml, common/k8s/Cargo.toml
Based on https://rustsec.org/advisories/RUSTSEC-2021-0003
Bumped the versions on both the manifest and lock files (newer non-breaking `kube` version).
=> Fix smallvec security vulnerability

Cargo.lock, Makefile, bin/tests/cli.rs, bin/tests/common.rs, common/fs/Cargo.toml, common/fs/src/cache/entry.rs, common/fs/src/cache/event.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs
This PR refactors the fs cache to use a lookup table to store entries rather manually maintaining a reference graph.
It also fixes #59
=> Harden fs module

Cargo.lock, Jenkinsfile, Makefile, bin/tests/cli.rs, bin/tests/common.rs, common/fs/Cargo.toml, common/fs/src/cache/entry.rs, common/fs/src/cache/event.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/http/Cargo.toml, common/k8s/Cargo.toml
fix: remove latest from Makefile publish image tags
docs: README.md, added command for viewing all available release tags, clarified process for running git command to view releases, fixed grammar issue
chore: Test improvements
chore: Make publishing image Jenkins step optional
chore: Bump smallvec version to address security vulnerability
fix: Refactor fs module to use slotmap instead of explicit reference graph
Co-authored-by: Jorge Bay Gondra <jorgebaygondra@gmail.com>
Co-authored-by: Tana M Berry <tana.berry@objectrocket.com>
Co-authored-by: Jorge Bay Gondra <jorgebaygondra@gmail.com>
=> 2.2.1 patch

docs/KUBERNETES.md, docs/OPENSHIFT.md
This should be more convenient then having to work within a checked out local branch when applying these resource sets.
This PR covers the 2.2 agent / branch.
=> Add direct resource links to k8s resource files (v2.2)

docs/KUBERNETES.md, docs/OPENSHIFT.md
This should be more convenient then having to work within a checked out local branch when applying these resource sets.
This PR covers the 3.0 agent / branch.
=> Add direct resource links to k8s resource files (v3.0)

Cargo.lock, common/config/Cargo.toml, common/config/src/lib.rs
This cleans up some more unsafe usage in the config module, in this case it was causing a use-after-free in my local tests.
=> Use hostname package to instead of libc

Cargo.lock, bin/Cargo.toml, bin/build.rs, bin/src/dep_audit.rs, bin/src/main.rs
Bonus PR while I'm waiting for builds.
This adds support for https://github.com/Shnatsel/rust-audit, which includes cargo lock metadata in the agent binaries themselves so that we can check the exact versions that were compiled into any given binary.
=> feat: Add 'auditable' to agent so we can track the dep versions

bin/tests/cli.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/journald/src/stream.rs
This patch replaces `unwrap()` and `expect()` calls that would cause thread panic with recoverable errors.
Ref: LOG-8421.
=> Use recoverable errors in fs cache

Cargo.lock, common/fs/Cargo.toml, common/fs/src/cache/dir_path.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/watch.rs
This changes the fs events stream so that it retains ordering of the underlying inotify events while pairing up the MovedFrom/MoveTo events.
=> buffer fs events while matching moved_to/moved_from

Cargo.lock, common/fs/src/cache/mod.rs, common/fs/src/tail.rs
Fixes infinite loop in `follow_links()` method and fixes `lookup()` to only return an `Option<EntryKey>` (instead of wrapped in a result).
=> Fix follow_links() loop and lookup()

bin/tests/cli.rs, common/config/src/raw.rs, common/fs/src/cache/mod.rs
Default glob rule `!(*.*)` was preventing directories w/ dot in their names to be considered.
This removes the rule and adds validation to include sub directories by default, regardless of the name.
Semver: minor
Ref: LOG-8788
This changes the default configuration, so we shouldn't include it in a patch release (the change in settings should not affect user in any case).
=> Support directories with dot in their names

docs/CODE_OF_CONDUCT.md
Switch links from Slack to Discourse and OSS email list.
=> docs(community): Point community away from Slack

docs/HELM.md
Document how to upgrade from the common archived charts repo to our own Helm repository charts.
It also includes information about how to use namespaces in Helm.
=> Document upgrading from archived Helm repo

bin/src/main.rs, common/fs/src/cache/entry.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/fs/src/tail.rs, common/journald/src/source.rs, common/journald/src/stream.rs, common/k8s/src/event_source.rs, common/k8s/src/middleware/metadata.rs, common/middleware/src/lib.rs
This is the first step toward stateful lookback.
It changes the tailer into a true multiplexed stream of lines from the various files the agent is tracking
=> feat: Split out TailedFile and flatten log line stream

Cargo.lock, common/http/Cargo.toml
PR for merge commit.
The idea is to keep `3.1` compatible with `master`.
In the future dependencies for the client and the buffer pool will diverge.
=> 3.1 into master

bin/tests/cli.rs, bin/tests/common.rs
Verifies the content of each line on `test_tags()`.
=> Tags integration test: verify each line contents

Cargo.lock, bin/src/main.rs, common/config/src/env.rs, common/config/src/lib.rs, common/config/src/raw.rs, common/fs/src/tail.rs, common/k8s/Cargo.toml, common/k8s/src/lib.rs, common/k8s/src/middleware/metadata.rs, docs/README.md
Adds backoff when handling with upstream k8s errors and supports disabling the use of k8s api altogether.
It also increases test coverage of k8s logic internals and config.
Ref: LOG-8885, LOG-8887 and LOG-8888.
This patch is out of scope of 3.1, so we have can merge it once 3.1 was released or start with 3.2 branch.
=> K8s improvements: backoff, small memoization and support disabling k8s log enrichment

common/fs/src/cache/tailed_file.rs
The new lazy lines tailer wasn't incrementing the lines metric.
=> Increment lines on lazy line codepath

common/k8s/Cargo.toml, common/k8s/src/middleware/metadata.rs
tower fails when there is no reactor running, use `tokio::test` macro.
=> Fix k8s test build

Cargo.lock, bin/src/main.rs, bin/tests/cli.rs, bin/tests/common.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/http/Cargo.toml, common/http/src/client.rs, common/state/src/lib.rs
This updates the Tailer to handle initialization of symlinks where their target files that are outside the tracked folders
=> 3.1 handle symlink init

bin/src/stream_adapter.rs, bin/tests/cli.rs, common/fs/src/cache/tailed_file.rs, common/fs/src/tail.rs, common/http/src/client.rs, common/http/src/lib.rs, common/state/src/lib.rs
This resolves an issue where symlinks to different hardlinks to the same underlying file were not being treated as the same file by the stateful lookback mechanism
=> Use inode instead of filepath as lookback key

Makefile, bin/tests/cli.rs
With the build image update, clippy is complaining about rule changes.
For 3.1 branch, ignore the new rules to prevent a binary change.
=> 3.1: Ignore new clippy errors

bin/tests/cli.rs, bin/tests/common.rs, common/fs/src/cache/dir_path.rs, common/fs/src/cache/mod.rs, common/fs/src/rule.rs, common/fs/src/tail.rs, common/http/src/retry.rs
Fix `from-over-into`, `ptr-arg` and `upper-case-acronyms` in `fs` and `http` crates
Relates to #127.
=> Handle new clippy warnings

k8s/agent-resources-openshift-supertenant.yaml, k8s/agent-resources-openshift.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml, k8s/mock-ingester.yaml
RBAC mode is stable since k8s v1.8.
We should also update the helm charts.
=> Use stable rbac.authorization.k8s.io/v1 API

bin/tests/cli.rs, common/fs/src/tail.rs
This splits out the event handling in the tailer into separate functions and flattens a lot of the if let x { Some(_) } else { None} logic
=> Refactor tailer to split out event handling

Jenkinsfile, Makefile
This refactors the Makefile's push-image target into it's components so they can be called separately from the Jenkinsfile and updates the Jenkinsfile to call them with the correct docker registry context
=> Add docker and icr registry password for Jenkinsfile

Dockerfile, Makefile, bin/Cargo.toml
This PR adds a FEATURES env var and threads it through to to the various cargo build commands.
It's used like:
FEATURES=profiling make build-image
It also adds the profiling feature to the binary to expose the jemallocator/profiling feature
=> Log 9461 - Expose jemalloc profiling feature

bin/src/main.rs, bin/tests/common.rs, bin/tests/retries.rs, common/config/src/lib.rs, common/config/src/raw.rs, common/http/src/client.rs, common/http/src/retry.rs, common/test/mock-ingester/src/lib.rs
It adds basic integration test coverage for retries by adding artificial delays to mock ingester responses.
I've added minor modifications to the client wrapper and to retry mod to support setting the retry parameters in the test.
=> Integration test for retries

common/config/src/lib.rs
A warn should be printed when log_k8s_events is enabled and k8s enrichment is disabled.
=> Fix k8s log warning condition

common/middleware/src/line_rules.rs
Break early when insert index is defined.
It fixes an edge case when multiple redactions are defined and multiple matches appear in the same line in a specific order.
It includes a unit test that was failing before the fix.
=> Fix redaction insert index

Cargo.lock, bin/Cargo.toml, bin/src/main.rs, bin/tests/cli.rs, bin/tests/cmd_line_env.rs, bin/tests/common.rs, common/config/src/argv.rs, common/config/src/lib.rs, common/config/src/raw.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/http/Cargo.toml, common/http/src/client.rs, common/http/src/lib.rs, common/http/src/metrics_endpoint.rs, common/journald/src/stream.rs, common/metrics/Cargo.toml, common/metrics/src/lib.rs, docs/INTERNAL_METRICS.md, docs/README.md
- Optionally expose a Prometheus endpoint.
- Add documentation for metrics.
- Create additional metrics, like a gauge for open files and a latency histogram.
=> Expose metrics in a Prometheus endpoint

bin/tests/cli.rs, bin/tests/common.rs
Adds coverage for "include-only" type of rules, using negative exclusion rules.
Related to #158.
=> Test include-only rules

bin/src/main.rs, common/k8s/src/middleware/metadata.rs
Sometimes the kube api might not be accessible as network
is not fully initialized (CNI). Retry with backoff and exit
in error when all attempts fail.
=> Support retries when fetching initial pod metadata

k8s/agent-resources-openshift-supertenant.yaml, k8s/agent-resources-openshift.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml, k8s/mock-ingester.yaml
Use `LOGDNA_INGESTION_KEY` in our own yamls. For future reference, `LOGDNA_AGENT_KEY` will continue to be supported (forever).
The change should not affect users' instrumentation as the `secretKeyRef` remains the same.
=> Use recommended env var for ingester key

Dockerfile, Jenkinsfile, Makefile, common/journald/Cargo.toml, docker/lib.sh
This adds the ability to build a completely static agent binary using musl.
The binary is still built in docker using the existing build-image command. to configure it set the STATIC env var to 1 when calling make build-image
=> Musl static build

bin/tests/cmd_line_env.rs, common/config/src/argv.rs, common/config/src/lib.rs
Print the current merged settings in yaml format and exit.
Useful for troubleshooting on production environments.
=> Support listing the current options

docs/LINUX.md
* Added some more detail about the compatibility of the agent with the listed Linux distros
* Deduped the install/upgrade instructions since it's safe for people in either camp to fully follow along with the appropriate instructions for their OS distribution type
*  Added some header notes in the relevant sections to cover our bases in terms of supporting these 3 end-users / scenarios
* User doing a new / fresh install of the *Linux* agent - notes aren't applicable to them, they can & should run every command in the instructions
* User upgrading from a older version of `logdna-agent-v2` - they can skip the `install logdna-agent` command if they've ever installed the Linux package for the current agent OR the legacy agent and just update their package. Running through these steps will also …
=> docs(linux): dedupe installation instructions and update conf desc

Jenkinsfile, bin/Cargo.toml, common/config/Cargo.toml, common/config/src/error.rs, common/fs/Cargo.toml, common/fs/src/rule.rs, common/k8s/Cargo.toml
This gets Aarch64 builds working.
Unfortunately I had to drop PCRE2 from config and switch kube-runtime over to rustls to get around compiler errors, so this is a bigger change than I'd hoped. Functionality changes should be minimal to zero though.
=> Get arm64 musl build working

Cargo.lock, common/test/mock-ingester/src/lib.rs
This updates the client library to a version including the Read fix and also changes the mock ingester to panic when it receives invalid payloads so that our integration tests can catch bad http requests
=> Update client to include Read impl fix

bin/tests/retries.rs
Adding an additional sleep seems to stabilise the test.
=> Fix retry test flakiness

docs/INTERNAL_METRICS.md, docs/LINUX.md
Edits per Chris' suggestions for removing the "Enable the agent"  section, and adding the `enable` step to be the last part of "Starting the agent" section.
=> Docs delete section

Makefile
RHEL 8 on ARM configures the kernel with a 65536 byte page size rather than the more usual 4k page size. By default Jemalloc picks up the page size on the build system and hard codes that into the binary.
Previously Jemalloc required it's compiled in page size to be the same as the system's in order to maintain alignment, however as of a year or so ago it now supports using a larger than native page size, at the cost of a small amount of performance.
This explicitly sets the jemalloc page size to 64k, I've tested the generated binary on both RHEL and Debian and it runs correctly on both.
=> Build static binaries with 64k page size

Jenkinsfile
* we've seen jobs hanging on Jenkins, so add a 1 hour timeout to prevent it
from continuing.
* looking at the recent jobs that passed, they took between 35 and 50 minutes,
so 1 hour should be enough, but we can bump this up if we see too many jobs
timeout
=> Add timeout to Jenkinsfile

Cargo.lock, bin/Cargo.toml, common/config/src/raw.rs, common/fs/src/cache/tailed_file.rs, common/http/src/client.rs, k8s/agent-namespace.yaml, k8s/agent-resources-openshift-supertenant.yaml, k8s/agent-resources-openshift.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml, k8s/mock-ingester.yaml
Bump Timeout to 25 seconds, default gzip ratio to "best" (9), and buffer size to 2.5MB which seemed to be about the right size.
The numbers above were obtained from testing against logs.logdna.com while the environment was under peak load.
=> Tweak buffer sizes and timeouts and raise some logging thresholds

bin/src/main.rs, common/http/src/client.rs, common/http/src/retry.rs, common/test/types/src/lib.rs
This lifts http error logic up to the top level and adds logic to clean up the retry files if the retry succeeds
=> Log 10787 cleanup retry files

bin/src/main.rs, bin/tests/http.rs, common/state/src/lib.rs
Attempt to create the configured state directory (db_path)  if it doesn't exist, handling invalid permissions by logging and skipping the creation. 
Ref: LOG-10638
=> fix: create state dir if possible

Cargo.lock, bin/Cargo.toml, bin/src/main.rs, bin/tests/common.rs, bin/tests/retries.rs, common/http/src/retry.rs, common/metrics/Cargo.toml, common/metrics/src/lib.rs
This ticket adds metrics for the following retry data points:
* pending files in the retry queue that have not been resent yet
* counts of successful retry ingest API calls
* counts of failed retry ingest API calls
* disk space used by all the current retry files
This is in addition to counts around the HTTP API calls around ingest API attempts, successes and failures. Tested via the included integration test that makes assertions around the metric properties instead of specific metric values.
Ref: LOG-10294
=> feat: Adding metrics to around ingest retry

Makefile
Fix Jenkins builds to ignore the chrono CVE for now while we wait for long term fixes from upstream packages as well as fixes to our code base.
=> build: ignore chrono CVE; awaiting long term fixes upstream

Makefile
Ignoring the new tokio RUSTSEC error for now to get the build pipelines restored. Opened LOG-11559 to bump tokio and the code next sprint.
=> build: fixing build for latest CVE warning

Cargo.lock, bin/Cargo.toml, common/fs/Cargo.toml, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/fs/src/cache/watch.rs, common/fs/src/tail.rs, common/http/Cargo.toml, common/http/src/retry.rs, common/journald/Cargo.toml, common/k8s/Cargo.toml, common/k8s/src/event_source.rs
This removes Chrono from as many places as we can to minimise the surface area affected by the setenv/localtime_r-in-multi-threaded-environment issue. The kube-rs project aren't planning on removing it immediately and there is a lot of debate over how best to handle it in general, so this is the best we can do I think.
=> de-chrono everything except kube module

Cargo.lock, bin/Cargo.toml, bin/src/main.rs, common/metrics/Cargo.toml, common/metrics/src/lib.rs, common/state/Cargo.toml
Bumps the rocksdb crate to the latest release in order to pick up changes around the jemalloc library (see https://github.com/rust-rocksdb/rust-rocksdb/pull/554). The PR also updates the agent to use tikv-jemallocator.
Ref: LOG-11566
=> fix: Bump rocksdb and jemallocator crates

bin/src/main.rs, common/http/src/retry.rs
In some circumstances around sending retry data, the code may attempt to remove a retry persistence file twice. Before this PR, we would log this as an error, now it will log a message as debug in case we need to troubleshoot further around the delete logic. The error message was needlessly harsh considering that the same end effect, the file was deleted, occurred whether or not a delete actually happened. 
Note: There is also the metric `logdna_agent_retry_storage_used` that can assist in alerting if files aren't actually be deleted.
Ref: LOG-11515
=> fix: more tolerant logging for retry file deletes

Cargo.lock, Makefile
Used `cargo update -p tokio` to bump the tokio version in the cargo.lock file to pick up the fix for RUSTSEC-2021-0124.
Ref: LOG-11559
=> fix: bump tokio version

Jenkinsfile
One of the difficulties encountered when trying to manually update and push out container images was constraint that one needed to manually confirm the publish step within the 5 minute timeout window from the Jenkins console. This PR updates the Jenkinsfile to include two boolean parameters to replace the two timeout prompts, with the default value for each prompt being `false`. The scheduled triggers set each parameter to `true` to maintain the weekly rebuild/publish schedule we had before.
=> build: Make image pub option Jenkins param

Makefile
This updates the makefile to use the newer build image tag format
=> Update the makefile to use the new split base images

Cargo.lock, Makefile, bin/Cargo.toml, bin/src/main.rs, bin/tests/cli.rs, bin/tests/common.rs, common/fs/Cargo.toml, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/fs/src/cache/watch.rs, common/fs/src/tail.rs, common/http/Cargo.toml, common/journald/Cargo.toml, common/k8s/Cargo.toml, common/k8s/src/errors.rs, common/k8s/src/event_source.rs, common/k8s/src/middleware/metadata.rs, common/source/Cargo.toml, common/state/Cargo.toml, common/state/src/lib.rs, common/test/mock-ingester/Cargo.toml, common/test/mock-ingester/src/bin/http_ingester.rs, common/test/mock-ingester/src/bin/https_ingester.rs, common/test/mock-ingester/src/lib.rs
This PR bumps the tokio version to 1.14.0, which is not affected by RUSTSEC-2021-0124. Given the age of this branch, this is a little more involved than bumping tokio version numbers. The first commit shows all the dependencies that also needed to be bumped with the move from tokio 0.2 to 1. The second commit shows all of the breaking API changes that needed modifications. The third commit is a small change to get unit tests to work.
Ref: LOG-11559
=> fix: bump tokio version to address CVE

Cargo.lock, bin/src/main.rs, bin/tests/cmd_line_env.rs, bin/tests/retries.rs, common/config/Cargo.toml, common/config/src/argv.rs, common/config/src/lib.rs, common/config/src/properties.rs, common/config/src/raw.rs, common/fs/src/rule.rs, common/http/src/limit.rs, common/http/src/retry.rs, common/journald/src/journalctl/mod.rs, common/state/src/lib.rs, docs/README.md
New configuration parameter now allows for limiting the amount of disk space the agent will use to store retry files. The usage is tracked across the sending and consuming retry structs and the disk usage metric now references that counter. Also updates the existing retry integration tests to separate out the retry directory used so each test now has a clean state on execution.
Ref: LOG-10296
=> feat: Retry disk space can be limited

common/config/src/raw.rs, common/fs/src/rule.rs, common/http/src/limit.rs, common/journald/src/journalctl/mod.rs, common/state/src/lib.rs
After updating the Jenkins build container images, we have some new linting rule failures that have been addressed in master as part of PR #279. This PR applies those changes to the 3.4 branch so we can build it again.
=> build: Picking main line linting fixes over

Cargo.lock, bin/Cargo.toml, bin/tests/cli.rs, bin/tests/common.rs, bin/tests/metrics.rs, bin/tests/retries.rs, common/k8s/src/middleware/metadata.rs, common/metrics/src/lib.rs, common/middleware/src/line_rules.rs
Building off the retry metrics work, this PR updates the existing metrics test case to not just check that metrics data points are defined. but also makes assertions about the captured values to ensure they are working as we intended. The test case also expands the number of metrics looked at, bringing the coverage to 12/15 metrics. 
I did find one metric that was never emitted in the code base and thus removed its definition.  
Ref: LOG-11063
=> test: hardening up the metrics integration test

Cargo.lock, Makefile, bin/src/main.rs, bin/tests/cli.rs, common/journald/Cargo.toml, common/journald/src/journalctl/mod.rs, common/journald/src/libjournald/source.rs, common/journald/src/libjournald/stream.rs, docker/journald/Dockerfile, docker/journald_dispatch.sh
The primary purpose of this PR are the changes to src/bin/main.rs to add a shutdown signal that can be triggered in the case of invalid configuration.
There are additional changes to fix the flakey journalctl tests and the build on more recent linux kernels which were causing jenkins and local development problems.
=> Add a shutdown signal to allow agent to exit on error

docs/README.md
This removes the extention-less files from the default values list and makes a note about including that pattern via environment variable.
=> Updated Defaults in README and Include Common Glob Pattern

Cargo.lock, Cargo.toml, bin/Cargo.toml, bin/tests/common.rs, bin/tests/metrics.rs, bin/tests/retries.rs, utils/metrics-recorder/Cargo.toml, utils/metrics-recorder/src/lib.rs
The PR is a prerequisite to #290. It pulls the existing `metrics-recorder` out of `bin/tests` and puts it into its own package so that it can be used in tests as well as bench.
=> Refactor Metrics Recorder

Cargo.lock, bench/Cargo.toml, bench/bin/throughput.rs
This PR extends to current benchmark project by collecting various metrics during the benchmark runtime. It then writes a summary of these metrics to STDOUT and  all gathered metrics to a `metrics_output.log` file.
Tests:
Ran on local machine as well as EC2 dev/test instance.
TODO:
=> Feat: Adds Metrics to Benchmark

Makefile
This tells docker to use the emulator to build non HOST arch docker images
=> Pass --platform to build-image to tell it to use the emulator

Makefile, bin/tests/cli.rs
This adds a wait to the start of the lookback integration tests so they wait for the agent to actually print some output before continuing with the test
=> Ensure test waits for agent to start

bin/tests/k8s.rs, docker/kind_dispatch.sh, docker/socat/Dockerfile, scripts/mk.k8s-test
- replaced "alpine/socat" image by local image built before tests
- increased wait time after pod startups to eliminate intermittent test failures (all platforms)  
LOG-12446
=> fix: k8s enrichment test always fails on ARM platform

Jenkinsfile, bin/tests/cli.rs
This fixes the 3.4 build on the new jenkins setup
=> Backport explicit Jenkins node label and integration test delay fix

Makefile
Docker has strange behaviour where it seems to remember the last image used for a particular tag. This can cause very strange behaviour if you use a non-host image with an explicit --platform arg and then go back to using a bare docker run
=> Add extra docker pull to make sure images are fixed up

Jenkinsfile
This fixes the broken sysdig scan step in CI ( the creds name was updated to sysdig-secure-api-token ) and adds a scan for the aarch64 image
=> Fix CI sysdig scan

bin/Cargo.toml, bin/tests/common.rs
The integration tests have to build the agent in the background in order to be able to test it.
Locally cargo caching seems to handle this fine and doesn't do any extra work, on jenkins it is slower (possibly slower disks when validating the build cache?).
This updates the spawn_agent function to cache the cargo build commands in a global so that only one build can execute at once per test binary and each subsequent build with a particular feature set will reuse the CargoRun command
=> Cache CargoBuild in integration tests

bin/src/main.rs, common/config/src/argv.rs, common/config/src/lib.rs, common/http/Cargo.toml
This is a very small change so that we now pass the cli args explicitly to Config rather than it reading from the environment itself.
This allows us to pass arguments to the unit test binaries again eg `cargo test -- --nocapture` without Config attempting to parse them and exiting when it finds an arg it doesn't understand.
=> Explicitly pass cli args to Config so that it doesn't try and parse the args for it's unit test binary

scripts/mk, scripts/mk.start.kind
- helper script for starting kind cluster with pre-loaded images for development
Test:
`kubectl cluster-info --context kind-agent-dev-cluster --kubeconfig ./docker/.kind_config_host`
LOG-12651
=> feat: helper script for starting kind cluster

Cargo.lock, bin/Cargo.toml
Very simple PR to specify a precise version of rustls which doesn't produce the ServerHelloDone log messages
=> Pin rustls to 0.20.2 as 0.20.3 and 0.20.4 have spurious error messages

Dockerfile, Dockerfile.debian, Dockerfile.debug, Jenkinsfile, Makefile, docker/journald_dispatch.sh, docker/kind/Dockerfile, docker/kind_dispatch.sh, docker/socat/Dockerfile, scripts/mk.start.kind, scripts/ubi8-sysroot.sh
Fix the docker container build so that the build links against the libraries from the target/distribution image rather than the build image.
=> Log 12405 update k8s builds to link against target image binaries

Makefile
Jenkins sets BUILD_TAG. This was resulting in images being created with a tag like `3.5.0-20220516.jenkin
s-logdna-logdna-agent-v2-3.5-27-amd64`. This PR changes things such that the first 16 characters of the sha256sum of the concatentation of the git short rev and the Jenkins branch build number to ensure uniqueness
=> Use VCS_REF and Jenkins BUILD_NUMBER to uniquely tag images

common/fs/src/tail.rs
Ignore newly introduced clippy lint warning.
Posted a ticket to refactor the fs module to remove the pattern that's provoking it: https://logdna.atlassian.net/browse/LOG-13066
=> clippy ignore

common/notify_stream/src/lib.rs
This raises the log level of a commonly hit log statement up to `trace!` rather than info!
=> Raise notify-stream log level from info to trace

Jenkinsfile
This backports the custom workspace change from master which improves the reliability of Jenkins jobs running on nodes with multiple executors
=> Backport custom jenkins workspace from master

Jenkinsfile
This prevents race conditions in the case where 2 agent builds are running at the same time in separate executors on the same Jenkins machine
=> Store AWS creds in Workspace in Jenkinsfile

docs/README.md
the readme is contradictory - the default value is never
/fixes 235
=> [DOCS] update readme to reflect default k8s events handling

Cargo.lock, common/fs/src/cache/tailed_file.rs, common/http/Cargo.toml, common/test/types/Cargo.toml
This bumps the logdna-rust client lib to 0.7.x
=> Bump to logdna-rust 0.7.x

Cargo.lock, common/config/src/raw.rs, common/fs/src/cache/tailed_file.rs, common/http/Cargo.toml, common/test/types/Cargo.toml
This adds a trivial custom deserializer for the Params field that first attempts to deserialize it as a ParamsBuilder object and ensures that hostname is correctly defaulted rather than failing to parse the config
=> Log 13584 deserialize params as paramsbuilder

common/fs/src/cache/mod.rs
This PR adds an additional field to the `FileSystem` struct to keep track of ignored file. It then uses the new field to keep from continuously logging about the same ignored file.
=> [Bug] Keep Track of Ignored Files to Prevent Verbose Logging

bin/tests/it/k8s.rs, common/config/src/lib.rs, docs/README.md
This changes the K8's lease startup default value from `off` -> `never`. The reason being that `off` is a special keyword in yaml so if, for some reason, a user wanted to explicitly set the default to `off`, they would need put the value in quotes to ensure it was handled as a string, i.e. `"off"`. 
With this change the default value is in line with other default values and doesn't need to be quoted if used explicitly.
=> [Fix] Change K8s Startup Lease Default Value

Cargo.lock, common/config/src/argv.rs, common/config/src/lib.rs, common/config/src/properties.rs, common/config/src/raw.rs, common/http/Cargo.toml, common/test/types/Cargo.toml
Had to completely rewrite the Params config handling to make it work properly in all cases.
=> Rewrite config params handling to use ParamsBuilder everywhere

Jenkinsfile
This sets the TOOLS_IMAGE_TAG env var when running under Jenkins. We need to do this as the gcr image tags that Jenkins uses are different from the docker.io tags that are set by default in the Makefile.
=> Set TOOLS_IMAGE_TAG in Jenkins environment

Cargo.lock, bin/src/_main.rs, bin/src/stream_adapter.rs, bin/tests/it/metrics.rs, bin/tests/it/retries.rs, common/config/src/argv.rs, common/config/src/lib.rs, common/fs/src/cache/mod.rs, common/fs/src/lookback.rs, common/fs/src/rule.rs, common/journald/src/journalctl/mod.rs, common/k8s/src/lease.rs, common/notify_stream/src/lib.rs, common/state/Cargo.toml, common/state/src/lib.rs, common/state/src/span.rs
* Address new lint errors
* Bump rocksdb to address RUSTSEC-2022-0046
* Bump Cargo.lock
=> Cherry pick back lint fixes and rocksdb bump from master

Cargo.lock, common/config/src/lib.rs
Fixes retry logging file location on windows specifically 
Test plan: Integration Test
Unit Test
 Manual Testing via observing leader logs 
Ref: LOG-13962
=> Log 13962 retry

Makefile
This
* Adds a new ignore for RUSTSEC-2022-0040 in owning_ref for cargo audit (which is only used in the bench tool, and not even the unsound code path)
* Bumps chrono to a version not affected by the underlying vulnerability in libc's `localtime_r`
=> Fix chrono rustsec and bump deps

Jenkinsfile, Makefile, packaging/windows/choco/mk_choco, packaging/windows/choco/mk_env, packaging/windows/choco/publish_to_choco, packaging/windows/msi/mezmo-agent.wxs, packaging/windows/msi/mk, packaging/windows/msi/mk_env, packaging/windows/msi/mk_msi, packaging/windows/msi/post_install.ps1, packaging/windows/msi/publish_to_s3
- added support for code signing of msi & exe using release cert
- 3 ways to sign: 
- 1) run "packaging/windows/msi/mk" using dev cert by default (debug) 
- 2)  run "WINDOWS=1 make msi-release" or "WINDOWS=1 make msi-debug"  (release & debug) 
- 3) run Jenkins build with PUBLISH_BINARIES param enabled (release)
=> release cert

common/config/src/argv.rs, docker/kind_start.sh
- set lookback default in help to 'none'
- now matches github doc
=> doc: fixed "lookback" default in help

Makefile
Fix the following error when running `make bench` without specifying `FEATURES=`
```
error: Package `bench v0.1.0 (/build/bench)` does not have the feature `libjournald`
```
=> Don't set default FEATURES for make bench

bin/tests/it/k8s.rs, common/k8s/src/middleware/metadata.rs, common/k8s/src/middleware/mod.rs, common/test/mock-ingester/src/lib.rs
Summary:
Parsing out container image and tag from appropriate container, sending via _meta object
Test Plan:
Manually test on web application
Unit tests
Ref: Log-10828
=> feat(image-tag): Add image name and tag to meta object

bin/src/service_main.rs
windows: added file rotation by size against log flood
=> Log 14607 windows add rotation by size for agent service log file

Cargo.lock, Jenkinsfile, bin/src/_main.rs, bin/tests/it/cli.rs, bin/tests/it/common.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/notify_stream/Cargo.toml, common/notify_stream/src/lib.rs
Updates `notify-rs` to version 5.0.0. The event objects have been completely refactored and the debouncer has been removed in v5. As a result the mapped events in the receiver method had to be refactored.
Testing:
- Linux unit and integration tests are all passing.
- Some Windows unit tests were failing due to strange macro issue. Wrote some work-round tests but QA to manually test these cases to ensure they exposing actual issues.
=> Update notify-rs to Version 5

Cargo.lock, bin/src/_main.rs, bin/tests/it/cli.rs, bin/tests/it/common.rs, common/config/src/argv.rs, common/config/src/env_vars.rs, common/config/src/lib.rs, common/config/src/properties.rs, common/config/src/raw.rs, common/fs/Cargo.toml, common/fs/src/cache/mod.rs, common/fs/src/tail.rs
- added config.log.clear_cache_interval, default is 6 hours
- fs tailer gets restarted periodically using clear_cache_interval to clear fs cache 
LOG_15140
=> feature: fs cache refresh

common/fs/src/cache/dir_path.rs
These two functions were added for the missing initial directory bug (#385). This fix currently only applies to Linux. As a result, when compiling on Windows, the compiler throws a warning about the functions not being used.
=> Fix Windows Compiler Warnings

common/notify_stream/src/lib.rs
- fixed panic during handling Rename-From notify-rs event with empty path
- it happens when From event is generated separately from To event due to some racing in notify-rs
- the event is ignored and rectified by explicit  FS rescan.
=> fix: panic at handling Rename notify-rs event with empty path

bin/src/main.rs, common/fs/src/cache/dir_path.rs, common/fs/src/cache/mod.rs, common/notify_stream/src/lib.rs
Some of that paths in Windows didn't include some of the crate modules and were throwing warnings.
=> Fix Trace Crate Windows Compiler Warnings

Cargo.lock, api/src/tailer/mod.rs, bin/src/_main.rs, bin/tests/it/cli.rs, common/config/src/lib.rs, common/fs/Cargo.toml, common/fs/src/cache/dir_path.rs, common/fs/src/cache/mod.rs
- agent is not able to start with logging directory that is missing on windows  - LOG-9806 regression on Windows
- typos
Ref: LOG-14549
Ref: LOG-9806
=> fix: non-existing log directory crash at startup on windows

Cargo.lock, Makefile, api/Cargo.toml, bin/Cargo.toml, common/config/Cargo.toml, common/fs/Cargo.toml, common/http/Cargo.toml, common/journald/Cargo.toml, common/k8s/Cargo.toml, common/middleware/Cargo.toml, common/test/types/Cargo.toml
- fixed name collision of local crate "http" in cargo audit run
- updated tempfile crate to "3.4.0"
- fixed windows build - removed unsupported flag "link-self-contained flag"
test:
- rustup update
- cargo audit --ignore RUSTSEC-2020-0071
=> fix: name collision of local crate "http" in cargo audit run

common/state/src/lib.rs
- enable compaction in rocksdb
- set rocksdb parameters based on memory budget
Ref: LOG-16224
=> fix: limit rocksdb rss memory usage

Cargo.lock, common/fs/Cargo.toml, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs
We have noticed some mystic error messages from the results of try_from which don't tell us where the issue is happening. This PR uses a drop in replacement of std::fs to extract better error messages that include the path and action
Ref: LOG-14646
=> chore: add better fs error messages to fs::cache::try_from

common/state/src/lib.rs
Looks like we aren't currently popping batches off the pending queue in the state tracking module
Ref: LOG-14646
=> fix: clear pending batches when processed

common/fs/src/cache/mod.rs, common/notify_stream/src/lib.rs, rust-toolchain.toml
- removed amplification of error "couldn't batch lines" + "file not found" - disabled retrying
- fixed rare panic in common/notify_stream/src/lib.rs in unwrap() when inotify event does not have path
- resolved clippy issue (choking on macro expansion) by pinning rust toolchain to previous version 1.69 using rust-toolchain.toml
Ref: LOG-14646
=> fix: "couldn't batch lines" log flood

bin/src/_main.rs, common/fs/src/cache/mod.rs
- added handling of condition when number of tracked files exceeds maximum number of open file descriptors ulimit
- primary error: "fs::cache: Processing notify event resulted in error: error reading file: Custom { kind: Uncategorized, error: Error<Too many open files (os error 24)"
- the error is treated as fatal with exit(24).
Test:
- with default ulimit 1024 copy 1200 new log files to log dir folder.
- expected: agent to exit with the panic message "Agent process has hit the upper limit of files it's allowed to open"
ref: LOG-17311
=> fix: log flood on "No file descriptors available" error

bin/src/_main.rs
- downgraded NotFound to debug
- ignoring by design
Ref: LOG-14615
=> fix: log flooded with error: Couldn't batch lines Io(Os { code: 3, knd: NotFound

Cargo.lock, bin/Cargo.toml, bin/src/_main.rs, bin/tests/it/k8s.rs, common/k8s/Cargo.toml, common/k8s/src/event_source.rs, common/k8s/src/kube_stats/pod_stats.rs, common/k8s/src/lib.rs, common/k8s/src/middleware/metadata.rs, common/k8s/src/middleware/mod.rs, common/k8s/src/middleware/runner.rs, common/middleware/src/lib.rs, common/state/src/lib.rs
In some cases, for unknown reasons, the k8s metadata watcher stream can
become inactive after receiving an error. This causes the cache to
become stale over time and for labels and annotations to be stale or
completely missing.
This PR fixes the issue by taking direct control of error handling on
stream errors and recreates the metadata watcher to start fresh.
Ref: LOG-16194
=> fix: refresh kubernetes metadata watcher on stream error

Cargo.lock, bin/Cargo.toml, bin/src/_main.rs, common/fs/Cargo.toml, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/k8s/Cargo.toml, common/k8s/src/middleware/metadata.rs, common/k8s/src/middleware/runner.rs
In some cases, logs ingested closed to when a pod is deleted might cause the logs to not be able to collect metadata information since the info has been removed from our cache. This fix makes sure that metadata info lives as long as the file exists to prevent this from happening.
=> fix: delay k8s metadata cleanup until file is deleted

Makefile, common/fs/src/cache/mod.rs
- followup change - fixed difference between MUSL & GNU libc error message
- added folder with build number to store backlog of binaries in S3
Ref: LOG-17311
=> fix: log flood on "No file descriptors available" error #2

Cargo.lock, bin/Cargo.toml, bin/src/_main.rs, bin/src/main.rs, common/fs/src/cache/mod.rs, utils/mock_ingester.py
- followup change - fixed error case in retry stream
- print "open files" system limits at startup (except windows)
Ref: LOG-17311
=> fix: log flood on "No file descriptors available" error #3

bin/src/_main.rs
Adds a memory cache of offsets to accurately manage the current state of offsets between filesystem restarts. This cache is completely separate from the db-persisted cache used by the client.
Ref: LOG-17217
=> fix: accurately track offsets between filesystem restarts

.dockerignore, Cargo.lock, api/Cargo.toml, bin/Cargo.toml, bin/src/_main.rs, bin/src/stream_adapter.rs, bin/tests/it/common.rs, bin/tests/it/k8s.rs, common/config/src/argv.rs, common/config/src/env_vars.rs, common/config/src/lib.rs, common/config/src/properties.rs, common/config/src/raw.rs, common/fs/src/cache/mod.rs, common/k8s/Cargo.toml, common/k8s/src/middleware/metadata.rs, common/k8s/src/middleware/mod.rs, common/k8s/src/middleware/runner.rs, common/middleware/Cargo.toml, common/middleware/src/k8s_line_rules.rs, common/middleware/src/lib.rs, common/middleware/src/line_rules.rs, common/middleware/src/meta_rules.rs
- added delayed lines source, parameterized by MZ_METADATA_RETRY_DELAY.
- "Lazy" lines can be "retried" - put back into delayed lines source queue based on result of validation of the line.
- the goal is to delay k8s lines that do not have pod metadata ready yet.
Ref: LOG-17820
=> feat: optionally delay processing of k8s log lines

Cargo.lock, common/config/src/argv.rs, common/config/src/env_vars.rs, common/config/src/lib.rs, common/config/src/properties.rs, common/http/Cargo.toml, common/http/src/limit.rs
- fix: log flood "hit rate limit snoozing"
- feat: print env config to log at startup (https://github.com/logdna/logdna-agent-v2/pull/548)
- fix:  missing _RGEEX suffix in envvar names:
LINE_EXCLUSION_REGEX,
LINE_INCLUSION_REGEX,
REDACT_REGEX,
Ref: LOG-11879,  LOG-18170
=> fix: log flood "hit rate limit snoozing"

Cargo.lock, bin/tests/it/cmd_line_env.rs, bin/tests/it/k8s.rs, common/config/src/lib.rs, common/config/src/raw.rs, common/fs/src/cache/dir_path.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/k8s/src/middleware/mod.rs, common/middleware/src/meta_rules.rs, common/test/types/src/strategies.rs
With rust 1.72 the old, no longer necessary, `Arc<Mutex<T>>` in fs is now causing a lint error. This PR replaces it with `RC<RefCell<T>>` where relevant. There are no functional changes.
This also fixes a couple of other lints, like using [T] instead of vec![] where possible and using try_fold where applicable
=> Remove no-longer-necessary Arc<Mutex<T>>

packaging/windows/msi/mezmo-agent.wxs
-- added -NoProfile to ps execution of post install script to avoid execution of current user profile scripts (repair case)
ref: LOG-17865
=> fix: CWE-269 Mezmo Agent <= 3.9.0 Local Elevation of Privileges

Cargo.lock, bin/Cargo.toml, bin/build.rs
This allows us to use rc.exe to link manifest files in they way visual studio usually does.
Before:
```
peres -v target/x86_64-pc-windows-msvc/release/logdna-agent.exe
WARNING: Resource directory VA is zero [at resources.c:582]
```
After:
```
DEBUG: id=0x10, dataOffset=0x80000018
DEBUG: id=0x1, dataOffset=0x80000030
DEBUG: id=0x409, dataOffset=0x48
DEBUG: CodePage=0, OffsetToData=19087456[0x1234060], Reserved=0[0], Size=472[0x1d8]
File Version:                    65263.1213.1.0
Product Version:                 3.6.0.0
```
This lets us embed fairly arbitrary information in the agent exe in a way that windows tooling expects (for example being able to set an icon that shows up in explorer etc, version information that appears in the file's property pane etc.)
This would also allow us to use …
=> feat: winres support

Makefile
=> fix: empty memory metrics reported when running on k8s

bin/src/_main.rs, bin/tests/it/cli.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs
Normally offsets are ignored when lookback is disabled, but filesystem offsets should still be respected. Filesystem offsets track state across internal filesystem offsets and differ from global offsets which track state across application restarts.
Before this change global offsets were always loaded and the filesystem would optionally respect them based on the lookback configuration. Now the filesystem always respect offsets regardless of lookback configuration, and global offsets are only loaded if the current lookback configuration respects global state.
Ref: LOG-17217
=> fix: respect filesystem offsets when lookback is disabled

Cargo.lock, Dockerfile, Makefile, bin/Cargo.toml, common/config/Cargo.toml, common/fs/Cargo.toml, common/http/Cargo.toml, common/journald/Cargo.toml, common/k8s/Cargo.toml, common/middleware/Cargo.toml, common/source/Cargo.toml
Pulls important security updates including
* RHSA-2023:5249
* https://github.com/advisories/GHSA-vh2x-5rx6-qqhv
This also makes the following changes:
1. Update the rust build image to latest for new features
2. Fix dependencies brought up by cargo audit
3. Change `http` crate to `mz-http` to avoid audit name collision
=> chore: update UBI base image to 8.8

Jenkinsfile
Pins the Jenkins agent to "rust-x86_64" so that builds always run on an appropriate node.
=> chore: pin jenkins agent to rust nodes

Jenkinsfile, common/http/src/client.rs
If response is one of either 500, 501, 502, 503, 504, 507, or 429; we should retry that request instead of just dumping it.
=> fix: retry requests on appropriate response codes

common/fs/src/cache/mod.rs
Not silently replacing fs entries, and instead returning an error, short circuits the logic that normally handles processing new files.
In cases where log rotation re-uses the same inodes, log rotation is seen as log truncation. Truncation is only detected during write events. If this event surpasses the internal 8196 byte limit, tailing will be picked up at the end of the file. This causes the first set of lines to be dropped.
By fixing this short circuiting issue, log truncation should now be correctly handled once the file is created. This should appropriately reset the offsets of the tailed file so the next write event begins properly at the beginning.
=> fix: silently replace existing fs entries

Cargo.lock, common/fs/Cargo.toml
A recent minor version change of "os_str_bytes" used by the fs package put some features we use behind the "conversions" feature flag. This adds that flag and regenerates the lockfile.
=> chore: enable conversions feature for os_str_bytes

docs/KUBERNETES.md, docs/README.md
* Add new configuration option for `MZ_METADATA_RETRY_DELAY`
* Remove maximum suggested memory limit
* Add section to Kubernetes for configuring metadata retry delay
=> docs: update various points in the documentation for 3.9

bin/tests/it/cli.rs, bin/tests/it/common.rs, common/fs/src/cache/mod.rs
Initial offsets never considered the current state of the file, instead just preferring to use the state saved offsets or defaulting to the value configured by the `MZ_LOOKBACK` option. This means truncation is handled downstream where the agent doesn't have enough contextual information to appropriately handle the case and potentially dropping logs.
This change causes initial offsets to be ignored if they exceed the current length of the file, and instead use the default values.
Ref: LOG-17217
=> fix: handle truncation while assigning initial offsets

Cargo.lock, bin/Cargo.toml, common/k8s/Cargo.toml
Version 0.86 of `kube` has been yanked, so updating to the current latest.
=> chore: update kube dependency to 0.87

Jenkinsfile, bin/tests/it/http.rs, bin/tests/it/k8s.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/http/src/retry.rs, utils/metrics-recorder/src/lib.rs
This change detangles applicaton auditing from image vulnerability updates. Auditing is now handled in a separate process. This change also adds slack alerting for both auditing and image vulnerability updates.
Ref: LOG-19259
=> ci: remove auditing from image vulnerability updates

common/k8s/src/event_source.rs
Clippy does not like complex blocks in the scrutinee of match statements.
Ref: LOG-19431
=> chore: fix clippy error

Jenkinsfile
A malformed cron string was preventing the audit cron from executing.
Ref: LOG-19430
=> ci: ensure audit cron fires

Dockerfile
Add additional microdnf update options to prevent unnecessary dependencies from being pulled in while building the final layer of the docker image.
Install systemd explicitly which was installed implicitly before.
Stops the docker image from being built with a version of python and pip vulnerable to CVE-2019-20916.
=> chore(docker): don't pull in unnecessary deps during update

Jenkinsfile, appveyor.yml, common/config/src/lib.rs, common/config/src/raw.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/http/src/retry.rs, common/k8s/src/kube_stats/node_stats.rs, common/middleware/src/line_rules.rs, common/test/mock-ingester/src/lib.rs
Set the minimum target version for macos builds to 10.14. Rocksdb fails to build for earlier versions.
Additionally includes a number of fixes for linter issues.
Finally fixes issue where the std dll was not found in appveyor builds because the toolchain was not in the path.
=> ci(macos): pin minimum version to 10.14

Cargo.lock, common/state/Cargo.toml, common/state/src/state.rs
Reverts rocksdb wrapper to 0.19.
This version of the agent is built on rocksdb 7.4.4 which is not compatible with version 0.22 of the rocksdb wrapper. Since this version of the agent is only receiving security updates and the previous versions of rocksdb and the wrapper don't have any security issues, let's just keep using the same version.
=> fix: static builds failing due to rocksdb

Cargo.lock, common/k8s/src/event_source.rs
Ran `cargo update` to update dependencies and to fix a couple high severity issues that was flagged during audit.
=> chore: update dependencies and fix audit errors

Jenkinsfile, Makefile
The regex we use to trigger Jenkins cronjobs for weekly runs only handles versions with single digits e.g. "3.9.0". This changes updates it to recognize any multidigit version e.g. "3.10.2".
Also adds a new Jenkins envvar "BUILD_SLUG" which is a docker tag friendly version of "BUILD_TAG".
=> ci: allow multidigit versions in weekly run check

Makefile, bin/tests/it/cli.rs, bin/tests/it/common.rs, common/fs/src/cache/entry.rs, common/fs/src/cache/guarded_option.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/symlinks.rs, common/fs/src/tail.rs
Track the targets of dangling symlinks for a watched directory to make sure it's not unwatched if it runs out of children. A couple of changed were made to achieve this:
1. Move `Symlinks` type to it's own struct and add helper functions.
2. Add new `dependencies` field to dir entries to track symlinks that target a child entry regardless if whether the symlink is broken or not.
3. When inserting paths from within the `insert` and `insert_helper` functions, don't run an unncessary rules check.
Additionally, the following changes and additions were made:
1. Split `Entry` enum into `Entry` struct and `EntryKind` enum.
2. Add new `GuardedOption<T>` to enable a toggleable option; used by symlink entries for their target to differentiate dangling symlinks without losing the underlying path.
3. …
=> fix(fs): ensure dangling symlinks are monitored correctly

Makefile
Ignore a vulnerability for one of our dependencies, `trust-dns-resolver` until a patch fix is available.
Also removes some outdated rustsec ignore rules which are no longer an issue.
=> chore: ignore RUSTSEC-2024-0421

Jenkinsfile, Makefile, bin/tests/it/cli.rs, bin/tests/it/cmd_line_env.rs, common/config/src/lib.rs, common/test/mock-ingester/src/lib.rs, docker/dispatch.sh, docker/journald/Dockerfile, docker/journald_dispatch.sh
Upgrades our build-image and tooling to bookworm. Bookworm also uses a newer version of systemd which is more modular - this enables us to set up a journald testing image without all systemd requirements which was broken on some hosts.
Additionally refactors the docker dispatch scripts to not utilize detached containers and instead run the commands directly. Additionally drops -j from make test call in Jenkins to make output easier to parse.
Finally disables some tests which try and access to `/etc/logdna` which doesn't seem to work anymore in our Jenkins environment.
Ref: LOG-21788
=> chore: upgrade to build-image and tooling to bookworm

Dockerfile, Dockerfile.debian, Dockerfile.debug, Jenkinsfile, docker/kind/Dockerfile, docker/socat/Dockerfile, scripts/ubi9-sysroot.sh
Updates the base image from from ubi8 -> ubi9. Additionally tracks down remaining references to bullseye and replace with bookworm.
Ref: LOG-22220
=> chore: update to ubi9
