Dockerfile
=> [LOG-5131] Switch the base image in the docker file from ubuntu to Red Hat's UBI

Cargo.lock, Jenkinsfile, Makefile, bin/Cargo.toml, bin/tests/cli.rs, docker/dispatch.sh
This PR adds a simple example integration test for the agent CLI.
It creates a temp dir, configures the agent to watch the temp dir, starts the agent, creates some files and checks that the agent successfully runs.
It does not currently validate that the expected events happen, only that it does not crash as long as a valid API key is present.
=> Integration test

docs/README.md
Paths referred to unreleased version
=> Changed paths in install to assets.logdna.com

Makefile
This dynamically generates a test- target for each sub crate allows which means you can run
make test-<component name>
and only run the unit tests for a specific sub-crate
eg `make test-fs` will run cargo test -p fs
Do you think this is useful enough to include @jakedipity?
=> Add dynamic targets for testing individual crates

Dockerfile
1. Update the base image from 8.2 -> 8.3
2. Remove the complicated build steps (used to optimize layer caching and build times) which is largely replaced by sccache
3. Combine a couple RUN commands together to shave off ~10MiB from the final image
=> Make a couple of changes to the Dockerfile

Cargo.lock, Makefile, bin/src/main.rs, common/config/Cargo.toml, common/config/src/env.rs, common/config/src/error.rs, common/config/src/lib.rs, common/config/src/raw.rs, common/fs/src/cache/dir_path.rs, common/fs/src/cache/mod.rs, common/fs/src/lib.rs, common/fs/src/tail.rs, common/http/src/limit.rs
=> Log 5684 lookback v1

common/fs/src/cache/mod.rs, common/fs/src/rule.rs
This fixes a panic if a cached filepath is non-utf8
=> Change fs rule matching to use PathBufs

Makefile
This changes the Makefile to include "today"'s date in the unique docker image tag
=> Tweak unique image tags to contain date

k8s/agent-resources-openshift-supertenant.yaml, k8s/agent-resources-openshift.yaml
=> Add OpenShift YAML files

Cargo.lock, Dockerfile, bin/Cargo.toml, docs/KUBERNETES.md, docs/OPENSHIFT.md, docs/README.md, k8s/agent-namespace.yaml, k8s/agent-resources-openshift-supertenant.yaml, k8s/agent-resources-openshift.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml, k8s/logdna-agent-st.yaml, k8s/logdna-agent.yaml, k8s/mock-ingester.yaml
Whoops, blew away the old PR with the branch...
This removes the DAC_READ capability and non-root docs for the 2.2 GA release
=> 2.2 beta.13

docs/README.md
Made changes for 2.2 GA release, mostly updated the Building Agent section to add clarity
=> updated the build image section, removed trademarks, minor edits

Cargo.lock, Jenkinsfile, Makefile, bin/tests/cli.rs, bin/tests/common.rs, common/fs/Cargo.toml, common/fs/src/cache/entry.rs, common/fs/src/cache/event.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/http/Cargo.toml, common/k8s/Cargo.toml
Once we merge this I can run make release-patch directly against the 3.0 branch which will bump versions and tag the commit directly on the 3.0 branch
=> 3.0.1 patch changes

bin/tests/cli.rs
=> Fix integration test to use AgentSettings struct

Cargo.lock, common/config/Cargo.toml, common/config/src/lib.rs
https://rustsec.org/advisories/RUSTSEC-2020-0100.html
Ref: LOG-8600
=> Replace sys-info dependency

common/k8s/src/middleware/metadata.rs
=> Log and continue on errors from the K8s resource

Makefile, bin/tests/cli.rs, bin/tests/common.rs, common/fs/src/tail.rs, docker/journald/Dockerfile
=> Remove entry after delete event

Cargo.lock, Makefile, bin/Cargo.toml, bin/build.rs, bin/src/dep_audit.rs, bin/src/main.rs, bin/tests/cli.rs, bin/tests/common.rs, common/config/Cargo.toml, common/config/src/lib.rs, common/fs/src/cache/mod.rs, common/fs/src/tail.rs, common/journald/src/stream.rs, common/k8s/src/middleware/metadata.rs, docker/journald/Dockerfile
This merges the error handling improvements and fix for the leaking file handles from master back onto 3.0.2
=> Merge 3.0.2

Cargo.lock, Makefile, common/fs/Cargo.toml, common/fs/src/cache/dir_path.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/watch.rs
* fix: buffer fs events while matching moved_to/moved_from
* fix: Make sure we don't delete directories
=> buffer fs events while matching moved_to/moved_from (#88)

Cargo.lock, common/fs/src/cache/mod.rs, common/fs/src/tail.rs
fix: Fix follow_links() loop and lookup()
chore: fix cargo-audit
=> Fix follow_links() loop and lookup() (#93)

Cargo.lock, common/fs/src/cache/mod.rs, common/fs/src/tail.rs
fix: Fix follow_links() loop and lookup()
chore: fix cargo-audit
Cherry pick fix to `master`.
=> Fix follow_links() loop and lookup()

Cargo.lock, bin/tests/cli.rs, bin/tests/common.rs, common/test/mock-ingester/Cargo.toml, common/test/mock-ingester/src/lib.rs
Integration test using the mock ingester to validate that tags are being sent.
=> Use mock ingester to test tags

Cargo.lock, Jenkinsfile, bin/Cargo.toml, bin/tests/cli.rs, bin/tests/common.rs, common/http/src/client.rs, common/journald/src/stream.rs, common/test/mock-ingester/src/lib.rs, docker/journald/Dockerfile
=> Add journald integration test

common/fs/src/cache/mod.rs
=> Handle open file errors (2.2)

common/fs/src/cache/mod.rs
=> Handle open file errors (3.0)

bin/tests/cli.rs
Test with file fsyncing at different positions, not necessarily at the end of the line.
=> Test partial fsynced lines

Cargo.lock, bin/src/main.rs, bin/tests/cli.rs, bin/tests/common.rs, common/config/src/env.rs, common/config/src/lib.rs, common/config/src/raw.rs, common/fs/Cargo.toml, common/fs/src/cache/tailed_file.rs, common/http/Cargo.toml, common/k8s/src/middleware/metadata.rs, common/middleware/Cargo.toml, common/middleware/src/lib.rs, common/middleware/src/line_rules.rs, docs/README.md
=>  Exclude, include and redact log lines via regex

docs/README.md
Document CPU and memory utilization on Kubernetes.
=> Resource usage docs

Jenkinsfile
=> Split image publish stage (#145)

docs/REGEX.md
Include regex for common PII patterns.
=> Common regex patterns for log redaction

docs/REGEX.md
Added Note about regex patterns not created/supported by LogDNA
=> added Note that patterns unsupported

common/fs/src/cache/mod.rs
Move events processed after parents have been removed, along with other path errors, were causing noise in the agent logs.
This patch creates a dedicated message for old move events and logs path errors (with the path) at debug level.
=> Use debug level for old move events and invalid path errors

common/journald/src/stream.rs
On some environments, seeking the tail of journald has no effect. I've only was able to reproduce it on IKS.
For example, these are journald messages 15+ days old:
In those case, we should continue processing the journald messages and avoid spamming the logs with info messages.
This PR prevents spamming the logs, producing only a maximum of a info every 5mins.
Before (more than info messages per second):
After the patch (set to 5s instead of 5m):
=> Journald: use a warn interval

common/config/src/argv.rs, docs/LINUX.md, docs/README.md
Installation and basic usage instructions for linux.
=> Add docs for installing in Linux

docs/KUBERNETES.md
I'm not sure that "local value"is the right way to word it.. please tweak as needed. Thanks!
=> Added a clarifying statement that the UID and GID don't have to be 5000

docs/LINUX.md
Provide installation and upgrade instructions for Linux.
=> Installation instructions for Linux with systemd

Cargo.lock, Makefile, bin/src/dep_audit.rs, bin/tests/cli.rs, bin/tests/cmd_line_env.rs, bin/tests/k8s.rs, bin/tests/retries.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/fs/src/tail.rs, common/journald/src/journalctl/mod.rs, common/k8s/src/event_source.rs, common/k8s/src/middleware/metadata.rs
The newer version of clippy has some complaints
=> fix lint errors

docs/INTERNAL_METRICS.md, docs/KUBERNETES.md, docs/LINUX.md, docs/README.md
Made updates to reflect decisions re lookback defaulting to `none`
=> updates per LOG-10523

docs/INTERNAL_METRICS.md, docs/KUBERNETES.md, docs/LINUX.md, docs/README.md
This time on 3.3... added the requested rewording about "Many users you will likely already have a configuration file..."
=> Docs more support edits

docs/KUBERNETES.md
Per the ticket, I added the "quick installation" steps that don't require cloning the repo. Let me know you thoughts about the placement and wording of it, etc., please.
=> added quick install steps per ticket

Cargo.lock, Makefile, bin/tests/cli.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/fs/src/cache/watch.rs, common/fs/src/tail.rs, common/http/src/client.rs
This addresses a couple of issues for agents running in high latency, high event volume environments
=> Log 10569 fixes

docs/KUBERNETES.md
agent-namespace.yaml was missing
=> Replaced agent-resources.yaml w agent-namespace.yaml in quick install steps

bin/src/main.rs, common/http/src/client.rs, common/http/src/retry.rs
This adds cleanup logic for retry files
=> Add retry file cleanup

Cargo.lock, common/http/src/batch.rs, common/http/src/retry.rs, common/test/types/Cargo.toml, common/test/types/src/lib.rs, common/test/types/src/strategies.rs
=> Retry unit testing

common/metrics/src/lib.rs
This PR is an initial attempt to implement issue #240 in the most backwards-compatible way, however I'd be just as happy to remove _millis from the existing metric and make it seconds-based.
=> add seconds metric to compliment millis metric for ingest histogram

Makefile, packaging/linux/after-upgrade, packaging/linux/before-remove, packaging/linux/logdna-agent.service
Add a build-deb target to Makefile to allow us to generate deb file
=> Add make build-deb target

Cargo.lock, Makefile, bin/src/main.rs, bin/tests/cli.rs, common/http/src/client.rs, common/http/src/limit.rs, docker/dispatch.sh
This resolves a problem where the agent was hanging under heavy load due to the runtime threads being put to sleep when the rate limited kicked in.
=> Log 11479 agent hang under heavy load

Cargo.lock, Makefile, bin/src/main.rs, bin/tests/cli.rs, bin/tests/common.rs, common/config/src/argv.rs, common/config/src/error.rs, common/config/src/lib.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/fs/src/lib.rs, common/fs/src/lookback.rs, common/fs/src/tail.rs, common/http/src/client.rs, common/http/src/limit.rs, common/http/src/retry.rs, common/state/Cargo.toml, common/state/src/lib.rs, common/state/src/offsets.rs, common/state/src/span.rs, common/test/mock-ingester/src/lib.rs, docker/dispatch.sh
This moves the lookback logic down into the tailer and fully adds batch support to the OffsetMap
=> Log 10775 segmented initial offsets

Makefile, bench/Cargo.toml, bench/bin/throughput.rs
This tweaks the benchmark to work with the new base image and to make it more verbose to make it slightly more debuggable.
=> Benchmarking tweaks

Jenkinsfile, Makefile
feat: arm64: enabled qemu based builds in Jenkins
LOG-11822
=> feat: arm64: enabled qemu based builds in Jenkins

Jenkinsfile, Makefile, bin/tests/cli.rs, common/fs/src/cache/mod.rs, common/k8s/src/event_source.rs, common/test/mock-ingester/src/lib.rs, scripts/mk
- added make targets for multi-arch images (arm64, amd64)
=> feat: added make targets for multi-arch images

Cargo.lock, Dockerfile, Makefile, bin/src/main.rs, bin/tests/cli.rs, common/k8s/src/errors.rs, common/k8s/src/event_source.rs, common/k8s/src/lib.rs, common/k8s/src/middleware/metadata.rs
This finishes off the refactor at #302 so that the k8s event api client ill also have it's user-agent set
=> Log 12327 ensure agent passes user agent to k8s api

Cargo.lock, Dockerfile, Dockerfile.debian, docs/KUBERNETES.md, k8s/agent-resources-no-cap.yaml, k8s/agent-resources-openshift.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml
- added agent-resources-no-cap.yaml for GKE Autopilot
- tested on GCP
LOG-12418
=> feat: support for GKE Autopilot

Jenkinsfile, Makefile, bin/tests/it/k8s.rs, docker/kind_dispatch.sh, docker/kind_stop.sh, scripts/mk.start.kind
- changed "make k8s" to use agent image from "make build-image-debian"
=> feat: changed "make k8s-test" to use agent image  from "make image-build-debian"

docker/kind_dispatch.sh, docker/kind_start.sh
Ensure leading `-` are stripped from the kind cluster name
=> Handle hyphens in kind cluster names better

Cargo.lock, bin/Cargo.toml, k8s/agent-namespace.yaml, k8s/agent-resources-no-cap.yaml, k8s/agent-resources-openshift-supertenant.yaml, k8s/agent-resources-openshift.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources.yaml, k8s/mock-ingester.yaml
Signed-off-by: Chris Nixon <chris.nixon@sigma.me.uk>
=> Bumping 3.6.0-dev to 3.6.0-beta.1

Cargo.lock, common/state/Cargo.toml, common/state/src/lib.rs
WIP: still requires a change to the base images
=> Bump rocksdb to address RUSTSEC-2022-0046

Cargo.lock, bin/src/_main.rs, bin/src/stream_adapter.rs, bin/tests/it/metrics.rs, bin/tests/it/retries.rs, common/config/src/argv.rs, common/config/src/lib.rs, common/fs/src/cache/mod.rs, common/fs/src/lookback.rs, common/fs/src/rule.rs, common/journald/src/journalctl/mod.rs, common/k8s/src/lease.rs, common/k8s/src/metrics_stats_aggregator.rs, common/notify_stream/src/lib.rs, common/state/Cargo.toml, common/state/src/lib.rs, common/state/src/span.rs
This addresses the new clippy lints from the next version of the rust toolchian
=> Address new lint errors

Makefile
fix: trailing ")" in MSI version
LOG-10066
=> fix: trailing ")" in MSI version

bin/Cargo.toml, k8s/agent-namespace.yaml, k8s/agent-resources-no-cap.yaml, k8s/agent-resources-openshift-supertenant.yaml, k8s/agent-resources-openshift.yaml, k8s/agent-resources-supertenant.yaml, k8s/agent-resources-with-reporter.yaml, k8s/agent-resources.yaml, k8s/mock-ingester.yaml
Signed-off-by: Chris Nixon <chris.nixon@sigma.me.uk>
=> Bumping 3.6.0-beta.1 to 3.7.0-dev

docs/README.md, docs/WINDOWS.md
- added reference to windows readme
=> reference to windows readme

Jenkinsfile, Makefile, packaging/windows/msi/mk_test
- added make targets: test-msi-release, test-msi-debug
- test:
-  runs on Linux using Wine
- integrated into Jenkins build
- checks installed files present
- checks exe version 
- checks signature presence
LOG-14321
=> test for msi installer using Wine

docs/README.md
Removed the `rustc` version dependency information. Also, made some formatting changes and added some new badges.
=> Update Version Information in README

docs/KUBERNETES.md, docs/OPENSHIFT.md
rewording k8s related references to stable as we have removed the tag.
LOG-13374
=> chore(doc): latest and stable cleanup

docs/README.md
=> Update Version Badge

docs/LINUX.md
-- added note about StateDirectory on Amazon Linux 2
=> note about StateDirectory

utils/mock_ingester.py
pip install flask
python mock_ingester.py
change these params in agent config:
host: localhost
use_ssl: false
=> mock ingester

appveyor.yml, bin/tests/it/cli.rs, common/fs/src/cache/mod.rs, common/middleware/src/meta_rules.rs, common/notify_stream/src/lib.rs
=> disable failing tests on Windows to unblock CI builds

docs/README.md
=> doc: clarified glob usage with additional example

docs/LINUX.md
=> doc: add non root instructions

common/fs/src/cache/mod.rs, common/notify_stream/src/lib.rs
This adds the `#[instrument]` attribute to the filesystem cache and notify-stream modules. This attribute exposes the function input and chains together method calls in the log output. Currently, I have it skipping most method output because of the verbosity. Set at the TRACE level.
Sample output:
```
TRACE process:insert:register_as_child:watch{self=Watcher { watcher: INotifyWatcher { channel: Sender { .. }, waker: Waker { inner: Waker { fd: File { fd: 22, path: "anon_inode:[eventfd]", read: true, write: true } } } }, rx: Receiver { .. } } path="/tmp/test-write/test_date3.log" mode=NonRecursive}: notify_stream: watching "/tmp/test-write/test_date3.log"
```
=> Add Instrument Attribute to Select Modules

appveyor.yml, docs/README.md, docs/WINDOWS.md
- doc
- disabled builds in CI on AV
=> doc: windows event logs

Jenkinsfile, Makefile, common/config/src/lib.rs, common/fs/src/lookback.rs, common/http/src/batch.rs, common/http/src/retry.rs
We were publishing the x86 binary to the aarch64-darwin-apple path when it should have been x86_64-darwin-apple path.
Ref: LOG-13026
=> ci: publish x86 darwin build to correct s3 path

common/k8s/src/middleware/metadata.rs
Adds logging that captures the name, namespace, labels, and annotations of pods that are captured by the k8s watcher stream. This is to help debug why some people are experiencing an edge case where the agent stops picking up labels.
Ref: LOG-16194
=> chore: add more logging to k8s watcher stream

common/k8s/src/middleware/metadata.rs
Before the k8s deletion stream would continuously poll the delete channel after it had closed. This change reworks the logic flow so that the deletion stream will instead close in this case given that it is non-recoverable.
Ref: LOG-17430
=> fix: allow k8s deletion stream to exit on closed delete channel

common/http/src/retry.rs
- treat Invalid Retry Directory as fatal error
Ref: LOG-17311
=> fix: Invalid Retry Directory is now treated as fatal error

Makefile
- added branch name to S3 path of build binaries
-
=> feat: added branch name to S3 path of build binaries

bin/tests/it/cli.rs
=> fix: added mock ingester to test_fs_rescan_on_initial_log_dir_delete

Cargo.lock, Cargo.toml, common/misc/rate-limit/.gitignore, common/misc/rate-limit/Cargo.toml, common/misc/rate-limit/README.md, common/misc/rate-limit/macro/Cargo.toml, common/misc/rate-limit/macro/README.md, common/misc/rate-limit/macro/src/lib.rs, common/misc/rate-limit/tests/rate_limit_tests.rs
- added new optional parameter for fallback code block
=> feat: rate-limit-macro: optional parameter for fallback code block

docs/KUBERNETES.md
Adding notes to kubernetes doc for new setting related to accounts sending logs from multiple clusters.
LOG-17924
=> chore(doc): add note for k8sclusterkey

Cargo.lock, common/fs/Cargo.toml, common/fs/src/cache/mod.rs
=> fix: log flood "Error tracking path No such file or directory"

common/config/src/lib.rs
=> feat: print RUST_LOG at startup

bin/src/_main.rs, bin/tests/it/k8s.rs
- fixed: lines w/o pod metadata did not go through full middleware processing
- added e2e verification to test_retry_line_with_missing_pod_metadata
ref: LOG-17820
=> fix: lines w/o pod metadata not sent right away

common/fs/src/cache/delayed_stream.rs
- fix intermittent test failures
=> fix: bumping latency check thr in test_delayed_queue

bin/src/_main.rs, bin/tests/it/metrics.rs, common/journald/src/journalctl/mod.rs, common/metrics/src/lib.rs
- new middleware metrics: ingress/egress/delayed/ignored/no-k8s-meta lines 
Ref: LOG-18315
=> feat: middleware metrics

Cargo.lock, Makefile.toml, bench/Cargo.toml, bin/Cargo.toml, bin/tests/it/cmd_line_env.rs, common/config/Cargo.toml, common/config/src/argv.rs, common/config/src/lib.rs, common/config/src/properties.rs, common/config/src/raw.rs, common/fs/Cargo.toml, common/fs/src/cache/delayed_stream.rs, common/fs/src/cache/mod.rs, common/fs/src/cache/tailed_file.rs, common/http/Cargo.toml, common/journald/Cargo.toml, common/k8s/Cargo.toml, common/k8s/src/metrics_stats_stream.rs, common/metrics/Cargo.toml, common/middleware/Cargo.toml, common/misc/rate-limit/Cargo.toml, common/misc/rate-limit/macro/Cargo.toml, common/notify_stream/Cargo.toml, common/state/Cargo.toml, common/state/src/span.rs, common/test/mock-ingester/Cargo.toml, common/test/mock-ingester/src/lib.rs, common/test/types/Cargo.toml
This relies on https://github.com/logdna/logdna-rust/pull/37
=> chore: bump and tidy deps

bin/src/_main.rs, common/http/src/client.rs
- retry 500s & 429
- more diag
- tested retries manually with utils/mock_ingester.py
=> Fix retries for successful 500s

bin/src/main.rs, utils/stress_test/stress_test.py
- added "end of main" log msg to track graceful shutdowns
- some makeups
=> feat: added "end of main" log msg to track graceful shutdowns

utils/stress_test/Dockerfile, utils/stress_test/README.md, utils/stress_test/run, utils/stress_test/stress_test.py
- typos in readme
- fixed container user
- added ingestor  port CLI option
- added run script
=> fix (stress test): readme. container user.

docs/HELM.md
showing how to set extraEnv when using helm to manage Agent
Ref: LOG-11023
=> doc: giving better instructions for helm

common/config/src/lib.rs
Trims whitespace from the read contents of the hostname. Adds additional warnings for reading errors instead of failing silently.
Ref: LOG-19260
=> fix: trim hostname whitespace

bin/src/stream_adapter.rs, bin/tests/it/main.rs, common/config/src/argv.rs, common/config/src/raw.rs, common/http/src/batch.rs, common/k8s/src/event_source.rs, common/k8s/src/kube_stats/container_stats.rs, common/k8s/src/kube_stats/node_stats.rs, common/k8s/src/kube_stats/pod_stats.rs
Fixes a handful of clippy warnings introduced through toolchain >= v1.82.0.
=> chore: fix clippy warnings

Jenkinsfile
Don't let windows block image publishing
=> chore: reorder jenkinsfile
